### ISSUE TITLE
Usage with @ngrx/store

### ISSUE THREAD

**Issue by st-clair-clarke** [aikoven/typescript-fsa#10]
Hi,
Interesting offering. Congrats.

Can it be used with @ngrx/store [https://github.com/ngrx/store](https://github.com/ngrx/store)

If so, an example please.

Thanks

**Comment by aikoven** [comment]
Give it a try!

I'm not using Angular, but since the only type this library takes from `redux` is `Action`, it could probably work.

My only doubt is that `Action.type` in `@ngrx/store` [is always `string`](https://github.com/ngrx/store/blob/v2.2.0/src/dispatcher.ts#L4), while in `redux` it [is `any`](https://github.com/reactjs/redux/blob/v3.6.0/index.d.ts#L17), which may lead to TypeScript errors.

**Comment by nitimmerman** [comment]
Hi all,
I've tried it and it actually works perfect!
My only concern is that redux is a dependency which brings it's own Action type but because both actions are FSA compliant it still works

**Comment by aikoven** [comment]
Just released [`typescript-fsa@2.0.0`](https://www.npmjs.com/package/typescript-fsa) with Redux dependency removed.

**Comment by nitimmerman** [comment]
You are a Hero!
Many thanks, will use that one

**Comment by aikoven** [comment]
I'm going to close this since the issue seems to be resolved. Please feel free to reopen if you have any trouble.

**Comment by matthewharwood** [comment]
@nitimmerman Do you have any code samples to show on using it fsa with ngrx?
