### ISSUE TITLE
2.1.0 breaking change; async start() with payload is now forbidden.

### ISSUE THREAD

**Issue by estaub** [aikoven/typescript-fsa#24]
So... I was using a real payload in async `.start()`, and now it won't even compile, which I suppose is a good thing, since it doesn't work.  Clearly this is intentional; there's even a test to make sure payloads aren't allowed.

Semver, please?  If you're going to deliberately break stuff that works now, bump the major rev number.

Falling back to 2.0 for now.  Please let me know if this (i.e., forbidding `.start()` payload) is permanent.

**Comment by aikoven** [comment]
I am truly sorry about this, payloads are meant to be allowed for `.started()` action creators, the `2.1.0` version only makes it possible to skip the payload if its type is `undefined`. As you can see [here](https://github.com/aikoven/typescript-fsa/commit/729b73aecbeb21565c854be27d3da0e97bcbc288) we only added a new signature and old ones are still there. But for some reason TypeScript selects the wrong signature when you declare async action creator with non-`undefined` payload type.

I will revert and deprecate version `2.1`. You can use `2.0` for now since there weren't any other changes.

**Comment by aikoven** [comment]
Released `2.2.0`.

**Comment by estaub** [comment]
@aikoven Thanks, and sorry to go off on you a bit.  I misread one the tests, then inferred nonexistent intent.

**Comment by tblaisot** [comment]
@aikoven Couldn't you have the same result by declaring the payload field of Action<P> non mandatory ? I tried this solution (with all fields related to payload like params, etc...) and i think you lose nothing in term of the security of the typings.
By doing so you can even remove the EmptyActionCreator type.

**Comment by aikoven** [comment]
@tblaisot We'd lose the ability for the compiler to tell us if there is a payload or not, which we currently have with `strictNullChecks` enabled.

**Comment by aikoven** [comment]
I'm going to close this now, please feel free to reopen if there's a case.
