### ISSUE TITLE
Usage with redux connect

### ISSUE THREAD

**Issue by clouddra** [aikoven/typescript-fsa#32]
I was trying to do the following

```typescript
import * as actions from '../actions/actions';
import {ActionCreatorsMapObject} from "redux";

export default connect(state => state, (dispatch) => {
  return bindActionCreators(actions, dispatch);
})(someComponent);
```
and I got the following error
```
 error TS2345: Argument of type 'typeof ".../actions/actions"' is not assignable to parameter of type 'ActionCreatorsMapObject'.
```

as a workaround i had to do 
```typescript
import * as actions from '../actions/actions';
import {ActionCreatorsMapObject, bindActionCreators} from "redux";

export default connect(state => state, (dispatch) => {
  return bindActionCreators(actions as any as ActionCreatorsMapObject, dispatch);
})(temp);
```

or alternatively
```typescript
import * as actions from '../actions/actions';
import {ActionCreatorsMapObject, bindActionCreators} from "redux";

export default connect(state => state, (dispatch) => {
  return bindActionCreators({...actions}, dispatch);
})(temp);
```

I am not sure if it is a mismatch of type signatures or the typescript module system

**Comment by aikoven** [comment]
I am sorry for the late reply.

I don't think that assigning a module object to an index signature would work in TypeScript. 

A possible workaround might be to `export default` an object with all action creators.

But I wouldn't recommend this pattern because it creates a new function per action per connected component, which is expensive. I'd suggest to only bind action creators that you actually use in your component.

**Comment by rasdaniil** [comment]
Btw, in case we need to pass all actionCreators to a component, the typings of Props could be simply extended with help of `typeof`:

````
import * as actions from '.../actions.ts';
type Props = { ..otherProps.. } & typeof actions;

// later on
connect(null, actions)...

// later on in the component

props.myAction(payload);

```
